package Model.Enums;

public enum Carts {
    arcanitereaper,
    ashbringer,
    blessingoftheancients,
    bloodfury,
    bookofspecters,
    cobaltspellkin,
    curiocollector,
    darkskies,
    deadlyshot,
    deathwing,
    depthcharge,
    divinehymn,
    dreadscale,
    evasivewyrm,
    fierywaraxe,
    flamestrike,
    friendlysmith,
    gearblade,
    highpriestamet,
    holylight,
    koboldstickyfinger,
    learndraconic,
    lightforgedblessing,
    pharaohblessing,
    polymorph,
    sandbreath,
    sathrovarr,
    securityrover,
    silversword,
    sprint,
    strengthinnumbers,
    swampkingdred,
    swarmoflocusts,
    tastyflyfish,
    tombwarden,
    truesilverchampion,
    umbralskulker,



}